=== futre153/bb/EventManager/conf2/DistrListSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.example.org/DistrListSchema" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.example.org/DistrListSchema">



    




    

    <xsd:complexType name="AdrList">
    	<xsd:sequence>
    		<xsd:element name="name" type="AdrItem" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
        <xsd:attributeGroup ref="AdrItemAtt"></xsd:attributeGroup>
    </xsd:complexType>

    <xsd:complexType name="AdrItem">
    	<xsd:simpleContent>
    		<xsd:extension base="AdritemType">
    			<xsd:attribute name="enabled" type="xsd:boolean" use="required"></xsd:attribute>
    		</xsd:extension>
    	</xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="AdritemType">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[a-z]+ [a-z]+"></xsd:pattern>
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:attributeGroup name="AdrItemAtt">

    	<xsd:attribute name="main" use="required">
    		<xsd:simpleType>
    			<xsd:restriction base="xsd:string">
    				<xsd:pattern value="[a-z]+ [a-z]+"></xsd:pattern>
    			</xsd:restriction>
    		</xsd:simpleType>
    	</xsd:attribute>
    	<xsd:attribute name="separator">
    		<xsd:simpleType>
    			<xsd:restriction base="xsd:string">
    				<xsd:enumeration value="."></xsd:enumeration>
    				<xsd:enumeration value="-"></xsd:enumeration>
    			</xsd:restriction>
    		</xsd:simpleType>
    	</xsd:attribute>
    	<xsd:attribute name="domain">
    		<xsd:simpleType>
    			<xsd:restriction base="xsd:string">
    				<xsd:enumeration value="pabk.sk"></xsd:enumeration>
    			</xsd:restriction>
    		</xsd:simpleType>
    	</xsd:attribute>
    </xsd:attributeGroup>

    <xsd:complexType name="DLSequnce">
    	<xsd:sequence minOccurs="1">
    		<xsd:element name="address-list" type="AdrList"></xsd:element>
    		<xsd:element name="address-group-list" type="AdrGrpList">
    		</xsd:element>
    		<xsd:element name="condition-list" type="CondList"></xsd:element>
    		<xsd:element name="msg-list" type="MsgListType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="distribution-list" type="DLSequnce"></xsd:element>

    <xsd:complexType name="AdrGrpList">
    	<xsd:sequence minOccurs="0" maxOccurs="unbounded">
    		<xsd:element name="address-group" type="AdrGrpItem"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="AdrGrpItem">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="name" type="GrpItem"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="groupName" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="GrpItem">
    	<xsd:simpleContent>
    		<xsd:extension base="GrpitemType"></xsd:extension>
    	</xsd:simpleContent>
    </xsd:complexType>
    
    <xsd:simpleType name="GrpitemType">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[a-z]+ [a-z]+"></xsd:pattern>
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="CondList">
    	<xsd:sequence minOccurs="0" maxOccurs="unbounded">
    		<xsd:element name="condition" type="conditionType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:attributeGroup name="CondAtt">
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="priority" type="xsd:string" use="required"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:complexType name="conditionType">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="condition-item" type="CondItemType"></xsd:element>
    	</xsd:sequence>
        <xsd:attributeGroup ref="CondAtt"></xsd:attributeGroup>
    </xsd:complexType>

    <xsd:complexType name="CondItemType">
    	<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="group" type="xsd:string"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="regExp" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="MsgListType">
    	<xsd:sequence minOccurs="0" maxOccurs="unbounded">
    		<xsd:element name="message-template" type="MsgTmplType"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="encoding" type="encodingType" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="MsgTmplType">
    	<xsd:sequence minOccurs="1">
    		<xsd:element name="recipients" type="RcpType"></xsd:element>
    		<xsd:element name="subject" type="xsd:string"></xsd:element>
    		<xsd:element name="body" type="bodyType"></xsd:element>
    		<xsd:element name="attachments" type="AttType"></xsd:element>
    	</xsd:sequence>
        <xsd:attributeGroup ref="MsgTmplAtt"></xsd:attributeGroup>
    </xsd:complexType>

    <xsd:complexType name="RcpType">
    	<xsd:sequence minOccurs="0" maxOccurs="unbounded">
    		<xsd:element name="group" type="RcpItem"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="type" type="OperType" use="required"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:simpleType name="groupType">
    	<xsd:restriction base="xsd:string"></xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="AttType">
    	<xsd:sequence minOccurs="0" maxOccurs="2">
    		<xsd:element name="attachment" type="xsd:string"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="bodyType">
    	<xsd:sequence minOccurs="0" maxOccurs="unbounded">
    		<xsd:element name="line" type="lineType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>



    <xsd:attributeGroup name="MsgTmplAtt">
    	<xsd:attribute name="class" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="encoding">
    		<xsd:simpleType>
    			<xsd:restriction base="encodingType">
    				<xsd:enumeration value="utf-8"></xsd:enumeration>
    			</xsd:restriction>
    		</xsd:simpleType>
    	</xsd:attribute>
    	<xsd:attribute name="condition" type="xsd:string"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:simpleType name="encodingType">
    	<xsd:restriction base="xsd:string"></xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="OperType">
    	<xsd:restriction base="xsd:string">
    		<xsd:enumeration value="fixed"></xsd:enumeration>
    		<xsd:enumeration value="and"></xsd:enumeration>
    	</xsd:restriction>
    </xsd:simpleType>


    <xsd:complexType name="RcpItem">
    	<xsd:simpleContent>
    		<xsd:extension base="xsd:string">
    			<xsd:attribute name="condition" type="xsd:string"></xsd:attribute>
    		</xsd:extension>
    	</xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="lineType">
    	<xsd:simpleContent>
    		<xsd:extension base="xsd:string">
    			<xsd:attribute name="condition" type="xsd:string"></xsd:attribute>
    		</xsd:extension>
    	</xsd:simpleContent>
    </xsd:complexType>
</xsd:schema>

=== futre153/bb/EventManager/conf2/distribution_list2.xml
<?xml version="1.0" encoding="UTF-8"?>
<distribution-list xmlns="http://www.example.org/DistrListSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/DistrListSchema DistrListSchema.xsd ">
  <br/>
  <link janoe = "peter" />
  <address-list main="branislav brandys" separator="." domain="pabk.sk">
  	<name enabled="false">daniela stefanovicova</name>
	<name enabled="false">dana urbankova</name>
	<name enabled="true">nina poloncova</name>
	<name enabled="true">branislav brandys</name>
	<name enabled="false">stanislav kudlac</name>
	<name enabled="false">jana lacna</name>
	<name enabled="true">jana lobbova</name>
	<name enabled="true">martina glittova</name>
	<name enabled="true">zuzana stevlikova</name>
	<name enabled="true">darina valentova</name>
	<name enabled="true">viera zemancova</name>
	<name enabled="false">michaela sobolicova</name>
	<name enabled="false">tomas krehel</name>
	<name enabled="true">andrea tothova</name>
	<name enabled="false">denisa bartalosova</name>
	<name enabled="true">blanka javorska</name>
	<name enabled="true">lucia tejgiova</name>
	<name enabled="true">martina horvathova</name>
	<name enabled="true">branislav balaz</name>
	<name enabled="false">zoltan allo</name>
	<name enabled="false">bohuslav ukropec</name>
	<name enabled="true">daniel hajdiak</name>
	<name enabled="false">matej darovec</name>
	<name enabled="true">branislav fasung</name>
	<name enabled="false">martin novak</name>
	<name enabled="true">alzbeta zahumenska</name>
	<name enabled="true">peter suba</name>
	<name enabled="false">marian pallay</name>
	<name enabled="true">stanislav racek</name>
	<name enabled="true">peter glasa</name>
	<name enabled="true">zuzana bartalova</name>
	<name enabled="true">juraj macko</name>
	<name enabled="true">alena purdekova</name>
	<name enabled="false">eva kosikova</name>
	<name enabled="true">radka kalnassyova</name>
	<name enabled="true">miroslava drzkova</name>
	<name enabled="true">martin jelenciak</name>
	<name enabled="true">tibor kovacs</name>
	<name enabled="true">eva kleinova</name>
	<name enabled="true">katarina silhanova</name>
	<name enabled="false">stanislav mihalovic</name>
	<name enabled="true">julia bohacova</name>
	<name enabled="true">lucia gombikova</name>
	<name enabled="true">zuzana holescakova</name>
	<name enabled="true">katarina polakovicova</name>
  </address-list>
  <address-group-list>
  	<address-group groupName="zps">
  		<name>nina poloncova</name>
  		<name>zuzana stevlikova</name>
  		<name>andrea tothova</name>
  		<name>eva kleinova</name>
  		<name>katarina silhanova</name>
  		<name>lucia gombikova</name>
  	</address-group>
  	<address-group groupName="mt7XX">
  		<name>nina poloncova</name>
  		<name>andrea tothova</name>
  	</address-group>
  	<address-group groupName="dealing">
  		<name>branislav fasung</name>
  		<name>zuzana holescakova</name>
		<name>alzbeta zahumenska</name>
  		<name>peter suba</name>
  	</address-group>
  	<address-group groupName="middleOffice">
  		<name>darina valentova</name>
  		<name>blanka javorska</name>
  		<name>radka kalnassyova</name>
  		<name>miroslava drzkova</name>
  	</address-group>
  	<address-group groupName="backOffice">
  		<name>viera zemancova</name>
  		<name>blanka javorska</name>
  		<name>martin jelenciak</name>
  		<name>tibor kovacs</name>
  	</address-group>
  	<address-group groupName="mt5XX">
  		<name>daniel hajdiak</name>
  		<name>stanislav racek</name>
  		<name>peter glasa</name>
  		<name>juraj macko</name>
  		<name>alena purdekova</name>
  	</address-group>
  	<address-group groupName="boSecurities">
  		<name>blanka javorska</name>
  		<name>lucia tejgiova</name>
  		<name>martina horvathova</name>
  		<name>branislav balaz</name>
  	</address-group>
  	<address-group groupName="colpliance">
  		<name>andrea tothova</name>
  		<name>julia bohacova</name>
  	</address-group>
  	<address-group groupName="dit">
  		<name>branislav brandys</name>
  	</address-group>
  	<address-group groupName="pdm">
  		<name>nina poloncova</name>
  		<name>eva kleinova</name>
  		<name>zuzana stevlikova</name>
  		<name>katarina polakovicova</name>
  	</address-group>
  </address-group-list>
  <condition-list>
  	<condition name="trn" priority="4">
  		<condition-item regExp="NT.*">
  			<group>middleOffice</group>
  		</condition-item>
  		<condition-item regExp="N?[DFLNPS][BEOPRW][AOPW][DNOPT].*">
  			<group>backOffice</group>
  		</condition-item>
  		<condition-item regExp="\d{4}/\d{4}/\d{5}[BCc]?">
  			<group>zps</group>
  		</condition-item>
  		<condition-item regExp="\d{4}/\d{5}/\d{4}[BCc]?">
  			<group>zps</group>
  		</condition-item>
  		<condition-item regExp="[a-zA-Z]{4}/\d{4}">
  			<group>zps</group>
  		</condition-item>
  	</condition>
  	<condition name="fin" priority="1">
  		<condition-item regExp="7\d\d">
  			<group>mt7XX</group>
  		</condition-item>
  		<condition-item regExp="10\d">
  			<group>zps</group>
  			<group>middleOffice</group>
  		</condition-item>
  		<condition-item regExp="199">
  			<group>zps</group>
  		</condition-item>
  		<condition-item regExp="999">
  			<group>zps</group>
  			<group>backOffice</group>
  			<group>middleOffice</group>
  		</condition-item>
  		<condition-item regExp="2\d\d">
  			<group>middleOffice</group>
  			<group>backOffice</group>
  			<group>zps</group>
  		</condition-item>
		<condition-item regExp="9[0145]0">
			<group>middleOffice</group>
		</condition-item>
		<condition-item regExp="3\d\d">
			<group>backOffice</group>
		</condition-item>
		<condition-item regExp="[19]9[1256]">
			<group>zps</group>
		</condition-item>
		<condition-item regExp="5\d\d">
			<group>mt5XX</group>
			<group>dealing</group>
			<group>boSecurities</group>
		</condition-item>
  	</condition>
  	<condition name="event-number" priority="3">
  		<condition-item regExp="8[01][23][56]">
  			<group>zps</group>
  		</condition-item>
  	</condition>
	<condition name="queue" priority="4">
		<condition-item regExp="[M][o][n][e][y][L][a][u][n][d][e][r][i][n][g][IO][nu][t]?">
			<group>compliance</group>
		</condition-item>
		<condition-item regExp=".+">
			<group>dit</group>
		</condition-item>
	</condition>
	<condition name="event" priority="5">
		<condition-item regExp="trap">
			<group>zps</group>
			<group>middleOffice</group>
			<group>backOffice</group>
			<group>mt7XX</group>
			<group>boSecurities</group>
			<group>dit</group>
			<group>pdm</group>
		</condition-item>
	</condition>
  </condition-list>
  <msg-list encoding="utf-8">
  	<message-template class="trap10023" condition="MessagePartner=FileInput">
  		<recipients type="fixed">
  			<group>dit</group>
  		</recipients>
  		<subject>Správa o odoslaní dávky %Filename|shortName%</subject>
  		<body>
  			<line>Server:&#09;%SAA_IP_ADDRESS|lookup% (%SAA_IP_ADDRESS%)</line>
  			<line>Dávka:&#09;%Filename%</line>
  			<line>Odoslané správy:&#09;&#09;%InputMessagesAccepted|number%</line>
  			<line>Odmietnuté správy:&#09;%InputMessagesRejected|number%</line>
  			<line>Preskočené správy:&#09;%MessagesBypassed|number%</line>
  			<line></line>
  			<line>Status: %Result%</line>
  			<line></line>
  			<line>Ak sa táto správa nevzťahuje na Vás, prosím považujte ju za bezpredmetnú.</line>
  			<line></line>
  			<line>V prípade akýchkoľvek nejasností kontaktujte: %ID|mainRecipient%</line>
  		</body>
  		<attachments/>
  	</message-template>
  	<message-template class="trap10023" condition="MessagePartner=FileInputCZ">
  		<recipients type="fixed">
  			<group>dit</group>
  		</recipients>
  		<subject>Správa o odoslaní dávky %Filename|shortName%</subject>
  		<body>
  			<line>Server:&#09;%SAA_IP_ADDRESS|lookup% (%SAA_IP_ADDRESS%)</line>
  			<line>Dávka:&#09;%Filename%</line>
  			<line>Odoslané správy:&#09;&#09;%InputMessagesAccepted|number%</line>
  			<line>Odmietnuté správy:&#09;%InputMessagesRejected|number%</line>
  			<line>Preskočené správy:&#09;%MessagesBypassed|number%</line>
  			<line></line>
  			<line>Status: %Result%</line>
  			<line></line>
  			<line>Ak sa táto správa nevzťahuje na Vás, prosím považujte ju za bezpredmetnú.</line>
  			<line></line>
  			<line>V prípade akýchkoľvek nejasností kontaktujte: %ID|mainRecipient%</line>
  		</body>
  		<attachments/>
  	</message-template>
  	<message-template class="trap10117">
  		<recipients type="and">
  			<group condition="fin">UUMID|getFin</group>
  			<group condition="trn">UUMID|getReference</group>
  			<group condition="event">EventType</group>
  		</recipients>
  		<subject>Chyba formátovania správy</subject>
  		<body>
  			<line>MT%UUMID|getFin% do %UUMID|getBIC%, referencia: %UUMID|getReference%</line>
  			<line>Názov chyby:&#09;%SAA_EVENT_NAME|decodeB64%</line>
  			<line>Popis chyby:&#09;formát textu správy je pre tento typ správy nesprávny.</line>
  			<line></line>
  			<line>Chyba sa pravdepodobne nachádza na tomto mieste správy alebo tesne nad ním:</line>
  			<line>%@MessageInfo|decodeB64%</line>
  			<line></line>
  			<line>Text pôvodného chybového hlásania je v priloženom súbore.</line>
  			<line></line>
  			<line>Ak sa táto správa nevzťahuje na Vás, prosím považujte ju za bezpredmetnú.</line>
  			<line></line>
  			<line>V prípade akýchkoľvek nejasností kontaktujte: %ID|mainRecipient%</line>
  		</body>
  		<attachments>
  			<attachment>chybove_hlasenie.txt%SAA_EVENT_DESCRIPTION|decodeB64</attachment>
  		</attachments>
  	</message-template>
  	<message-template class="trap8005">
  		<recipients type="and">
  			<group condition="fin">UMID|getFin</group>
  			<group condition="trn">UMID|getReference</group>
  			<group condition="event">eventType</group>
  		</recipients>
