=== futre153/bb/PrepApp/WebContent/ngw_conf/CurrencyCodes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/CurrencyCodes" xmlns:cur="http://www.example.org/CurrencyCodes" elementFormDefault="qualified">

    <xsd:complexType name="CurrListType">
    	<xsd:sequence minOccurs="1" maxOccurs="1">
    		<xsd:element name="item" type="cur:CurrItemType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    
    <xsd:complexType name="CurrItemType">
    	<xsd:sequence minOccurs="0" maxOccurs="unbounded">
    		<xsd:element name="iso" minOccurs="1" maxOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:string">
    					<xsd:pattern value="[A-Z]{3}"></xsd:pattern>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="code" minOccurs="1" maxOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:string">
    					<xsd:pattern value="(\d{3})|(Nil)"></xsd:pattern>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="digits" minOccurs="1"
    			maxOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:string">
    					<xsd:pattern value="\d|\."></xsd:pattern>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="name" type="xsd:string" minOccurs="1"
    			maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="countries" type="cur:CtrsType" minOccurs="1" maxOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="CtrsType">
    	<xsd:sequence minOccurs="1" maxOccurs="1">
    		<xsd:element name="country" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:element name="list" type="cur:CurrListType"></xsd:element>
</xsd:schema>

=== futre153/bb/PrepApp/WebContent/ngw_conf/currency-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<cur:list 
    xmlns:cur="http://www.example.org/CurrencyCodes" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.org/CurrencyCodes CurrencyCodes.xsd ">
    <cur:item><cur:iso>AED</cur:iso><cur:code>784</cur:code><cur:digits>2</cur:digits><cur:name>United Arab Emirates dirham</cur:name><cur:countries><cur:country>United Arab Emirates</cur:country></cur:countries></cur:item><cur:item><cur:iso>AFN</cur:iso><cur:code>971</cur:code><cur:digits>2</cur:digits><cur:name>Afghan afghani</cur:name><cur:countries><cur:country>Afghanistan</cur:country></cur:countries></cur:item><cur:item><cur:iso>ALL</cur:iso><cur:code>008</cur:code><cur:digits>2</cur:digits><cur:name>Albanian lek</cur:name><cur:countries><cur:country>Albania</cur:country></cur:countries></cur:item><cur:item><cur:iso>AMD</cur:iso><cur:code>051</cur:code><cur:digits>2</cur:digits><cur:name>Armenian dram</cur:name><cur:countries><cur:country>Armenia</cur:country></cur:countries></cur:item><cur:item><cur:iso>ANG</cur:iso><cur:code>532</cur:code><cur:digits>2</cur:digits><cur:name>Netherlands Antillean guilder</cur:name><cur:countries><cur:country>Curaçao (CW)</cur:country><cur:country>Sint Maarten (SX)</cur:country></cur:countries></cur:item><cur:item><cur:iso>AOA</cur:iso><cur:code>973</cur:code><cur:digits>2</cur:digits><cur:name>Angolan kwanza</cur:name><cur:countries><cur:country>Angola</cur:country></cur:countries></cur:item><cur:item><cur:iso>ARS</cur:iso><cur:code>032</cur:code><cur:digits>2</cur:digits><cur:name>Argentine peso</cur:name><cur:countries><cur:country>Argentina</cur:country></cur:countries></cur:item><cur:item><cur:iso>AUD</cur:iso><cur:code>036</cur:code><cur:digits>2</cur:digits><cur:name>Australian dollar</cur:name><cur:countries><cur:country>Australia</cur:country><cur:country>Christmas Island (CX)</cur:country><cur:country>Cocos (Keeling) Islands (CC)</cur:country><cur:country>Heard and McDonald Islands (HM)</cur:country><cur:country>Kiribati (KI)</cur:country><cur:country>Nauru (NR)</cur:country><cur:country>Norfolk Island (NF)</cur:country><cur:country>Tuvalu (TV)</cur:country><cur:country>Australian Antarctic Territory</cur:country></cur:countries></cur:item><cur:item><cur:iso>AWG</cur:iso><cur:code>533</cur:code><cur:digits>2</cur:digits><cur:name>Aruban florin</cur:name><cur:countries><cur:country>Aruba</cur:country></cur:countries></cur:item><cur:item><cur:iso>AZN</cur:iso><cur:code>944</cur:code><cur:digits>2</cur:digits><cur:name>Azerbaijani manat</cur:name><cur:countries><cur:country>Azerbaijan</cur:country></cur:countries></cur:item><cur:item><cur:iso>BAM</cur:iso><cur:code>977</cur:code><cur:digits>2</cur:digits><cur:name>Bosnia and Herzegovina convertible mark</cur:name><cur:countries><cur:country>Bosnia and Herzegovina</cur:country></cur:countries></cur:item><cur:item><cur:iso>BBD</cur:iso><cur:code>052</cur:code><cur:digits>2</cur:digits><cur:name>Barbados dollar</cur:name><cur:countries><cur:country>Barbados</cur:country></cur:countries></cur:item><cur:item><cur:iso>BDT</cur:iso><cur:code>050</cur:code><cur:digits>2</cur:digits><cur:name>Bangladeshi taka</cur:name><cur:countries><cur:country>Bangladesh</cur:country></cur:countries></cur:item><cur:item><cur:iso>BGN</cur:iso><cur:code>975</cur:code><cur:digits>2</cur:digits><cur:name>Bulgarian lev</cur:name><cur:countries><cur:country>Bulgaria</cur:country></cur:countries></cur:item><cur:item><cur:iso>BHD</cur:iso><cur:code>048</cur:code><cur:digits>3</cur:digits><cur:name>Bahraini dinar</cur:name><cur:countries><cur:country>Bahrain</cur:country></cur:countries></cur:item><cur:item><cur:iso>BIF</cur:iso><cur:code>108</cur:code><cur:digits>0</cur:digits><cur:name>Burundian franc</cur:name><cur:countries><cur:country>Burundi</cur:country></cur:countries></cur:item><cur:item><cur:iso>BMD</cur:iso><cur:code>060</cur:code><cur:digits>2</cur:digits><cur:name>Bermudian dollar</cur:name><cur:countries><cur:country>Bermuda</cur:country></cur:countries></cur:item><cur:item><cur:iso>BND</cur:iso><cur:code>096</cur:code><cur:digits>2</cur:digits><cur:name>Brunei dollar</cur:name><cur:countries><cur:country>Brunei</cur:country><cur:country>auxiliary in  Singapore (SG)</cur:country></cur:countries></cur:item><cur:item><cur:iso>BOB</cur:iso><cur:code>068</cur:code><cur:digits>2</cur:digits><cur:name>Boliviano</cur:name><cur:countries><cur:country>Bolivia</cur:country></cur:countries></cur:item><cur:item><cur:iso>BOV</cur:iso><cur:code>984</cur:code><cur:digits>2</cur:digits><cur:name>Bolivian Mvdol (funds code)</cur:name><cur:countries><cur:country>Bolivia</cur:country></cur:countries></cur:item><cur:item><cur:iso>BRL</cur:iso><cur:code>986</cur:code><cur:digits>2</cur:digits><cur:name>Brazilian real</cur:name><cur:countries><cur:country>Brazil</cur:country></cur:countries></cur:item><cur:item><cur:iso>BSD</cur:iso><cur:code>044</cur:code><cur:digits>2</cur:digits><cur:name>Bahamian dollar</cur:name><cur:countries><cur:country>Bahamas</cur:country></cur:countries></cur:item><cur:item><cur:iso>BTN</cur:iso><cur:code>064</cur:code><cur:digits>2</cur:digits><cur:name>Bhutanese ngultrum</cur:name><cur:countries><cur:country>Bhutan</cur:country></cur:countries></cur:item><cur:item><cur:iso>BWP</cur:iso><cur:code>072</cur:code><cur:digits>2</cur:digits><cur:name>Botswana pula</cur:name><cur:countries><cur:country>Botswana</cur:country></cur:countries></cur:item><cur:item><cur:iso>BYR</cur:iso><cur:code>974</cur:code><cur:digits>0</cur:digits><cur:name>Belarusian ruble</cur:name><cur:countries><cur:country>Belarus</cur:country></cur:countries></cur:item><cur:item><cur:iso>BZD</cur:iso><cur:code>084</cur:code><cur:digits>2</cur:digits><cur:name>Belize dollar</cur:name><cur:countries><cur:country>Belize</cur:country></cur:countries></cur:item><cur:item><cur:iso>CAD</cur:iso><cur:code>124</cur:code><cur:digits>2</cur:digits><cur:name>Canadian dollar</cur:name><cur:countries><cur:country>Canada</cur:country></cur:countries></cur:item><cur:item><cur:iso>CDF</cur:iso><cur:code>976</cur:code><cur:digits>2</cur:digits><cur:name>Congolese franc</cur:name><cur:countries><cur:country>Democratic Republic of Congo</cur:country></cur:countries></cur:item><cur:item><cur:iso>CHE</cur:iso><cur:code>947</cur:code><cur:digits>2</cur:digits><cur:name>WIR Euro (complementary currency)</cur:name><cur:countries><cur:country>Switzerland</cur:country></cur:countries></cur:item><cur:item><cur:iso>CHF</cur:iso><cur:code>756</cur:code><cur:digits>2</cur:digits><cur:name>Swiss franc</cur:name><cur:countries><cur:country>Switzerland</cur:country><cur:country>Liechtenstein (LI)</cur:country></cur:countries></cur:item><cur:item><cur:iso>CHW</cur:iso><cur:code>948</cur:code><cur:digits>2</cur:digits><cur:name>WIR Franc (complementary currency)</cur:name><cur:countries><cur:country>Switzerland</cur:country></cur:countries></cur:item><cur:item><cur:iso>CLF</cur:iso><cur:code>990</cur:code><cur:digits>4</cur:digits><cur:name>Unidad de Fomento (funds code)</cur:name><cur:countries><cur:country>Chile</cur:country></cur:countries></cur:item><cur:item><cur:iso>CLP</cur:iso><cur:code>152</cur:code><cur:digits>0</cur:digits><cur:name>Chilean peso</cur:name><cur:countries><cur:country>Chile</cur:country></cur:countries></cur:item><cur:item><cur:iso>CNY</cur:iso><cur:code>156</cur:code><cur:digits>2</cur:digits><cur:name>Chinese yuan</cur:name><cur:countries><cur:country>China</cur:country></cur:countries></cur:item><cur:item><cur:iso>COP</cur:iso><cur:code>170</cur:code><cur:digits>2</cur:digits><cur:name>Colombian peso</cur:name><cur:countries><cur:country>Colombia</cur:country></cur:countries></cur:item><cur:item><cur:iso>COU</cur:iso><cur:code>970</cur:code><cur:digits>2</cur:digits><cur:name>Unidad de Valor Real (UVR) (funds code)[7]</cur:name><cur:countries><cur:country>Colombia</cur:country></cur:countries></cur:item><cur:item><cur:iso>CRC</cur:iso><cur:code>188</cur:code><cur:digits>2</cur:digits><cur:name>Costa Rican colon</cur:name><cur:countries><cur:country>Costa Rica</cur:country></cur:countries></cur:item><cur:item><cur:iso>CUC</cur:iso><cur:code>931</cur:code><cur:digits>2</cur:digits><cur:name>Cuban convertible peso</cur:name><cur:countries><cur:country>Cuba</cur:country></cur:countries></cur:item><cur:item><cur:iso>CUP</cur:iso><cur:code>192</cur:code><cur:digits>2</cur:digits><cur:name>Cuban peso</cur:name><cur:countries><cur:country>Cuba</cur:country></cur:countries></cur:item><cur:item><cur:iso>CVE</cur:iso><cur:code>132</cur:code><cur:digits>0</cur:digits><cur:name>Cape Verde escudo</cur:name><cur:countries><cur:country>Cape Verde</cur:country></cur:countries></cur:item><cur:item><cur:iso>CZK</cur:iso><cur:code>203</cur:code><cur:digits>2</cur:digits><cur:name>Czech koruna</cur:name><cur:countries><cur:country>Czech Republic</cur:country></cur:countries></cur:item><cur:item><cur:iso>DJF</cur:iso><cur:code>262</cur:code><cur:digits>0</cur:digits><cur:name>Djiboutian franc</cur:name><cur:countries><cur:country>Djibouti</cur:country></cur:countries></cur:item><cur:item><cur:iso>DKK</cur:iso><cur:code>208</cur:code><cur:digits>2</cur:digits><cur:name>Danish krone</cur:name><cur:countries><cur:country>Denmark</cur:country><cur:country>Faroe Islands (FO)</cur:country><cur:country>Greenland (GL)</cur:country></cur:countries></cur:item><cur:item><cur:iso>DOP</cur:iso><cur:code>214</cur:code><cur:digits>2</cur:digits><cur:name>Dominican peso</cur:name><cur:countries><cur:country>Dominican Republic</cur:country></cur:countries></cur:item><cur:item><cur:iso>DZD</cur:iso><cur:code>012</cur:code><cur:digits>2</cur:digits><cur:name>Algerian dinar</cur:name><cur:countries><cur:country>Algeria</cur:country></cur:countries></cur:item><cur:item><cur:iso>EGP</cur:iso><cur:code>818</cur:code><cur:digits>2</cur:digits><cur:name>Egyptian pound</cur:name><cur:countries><cur:country>Egypt</cur:country><cur:country>auxiliary in  Gaza Strip</cu
